sudo: required

jobs:
  include:
    - stage: test
      language: bash
      services:
      - docker
      before_script:
      - sudo curl -sSLo /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` && sudo chmod +x /usr/local/bin/docker-compose
      script: cd backend && make ci

    # note the node & yarn versions below need to be manually kept in sync with package.json (for now)
    - stage: test
      language: node_js
      node_js: '8.1.4'
      cache:
        directories:
          - frontend/node_modules
      install: skip
      before_script:
      - curl -sSL https://yarnpkg.com/install.sh | sudo bash -s -- --version 0.27.5
      script: cd frontend && make ci
