jobs:
  include:
    - stage: test
      language: bash
      env:
      - PATH="$HOME/.bin:$PATH"
      services:
      - docker
      before_script:
      - mkdir ~/.bin
      - curl -sSLo ~/.bin/docker-compose https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` && chmod +x ~/.bin/docker-compose
      script: cd backend && make ci

    # note the node & yarn versions below need to be manually kept in sync with package.json (for now)
    - stage: test
      language: node_js
      node_js: '8.1.4'
      env:
      - PATH="$HOME/.yarn/bin:$PATH"
      cache:
        directories:
        - frontend/node_modules
      install: skip
      before_script:
      - curl -sSL https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
      script: cd frontend && make ci
